---
# Note! - The task splitted into two different tasks because
#         in case one of the flavors provided without extra specs,
#         it will be ignored and not created

- name: copy shell script that executes elasticsearch query for flavor
  copy:
    src: query_flavor.sh
    dest: /tmp/query_flavor.sh
    owner: root
    group: root
    mode: 0755

- name: copy shell script that executes elasticsearch query for instance
  copy:  
    src: query_instance.sh
    dest: /tmp/query_instance.sh
    owner: root
    group: root
    mode: 0755 

- name: execute elasticsearch flavor query 
  shell: "/bin/bash /tmp/query_flavor.sh &"

- name: Check whether flavor creation log exist
  command: grep  test1 /tmp/output_flavor_query.txt
  register: checkmyconf
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Check whether flavor test1 was created and log recieved in Kibana.
  debug: msg="FLAVOR TEST1 WAS CREATED AND LOG SUCCESSFULLY RECIEVED IN KIBANA"
  when: checkmyconf.rc == 0


- name: execute elasticsearch instance query
  shell: "/bin/bash /tmp/query_instance.sh &"

- name: Check whether instance creation log exist
  command: grep  vm1 /tmp/output_instance_query.txt
  register: checkmyconf
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Check whether instance vm1 was created and log recieved in Kibana.
  debug: msg="INSTANCE VM1 WAS CREATED AND LOG SUCCESSFULLY RECIEVED IN KIBANA"
  when: checkmyconf.rc == 0
