---

- name: Openstack tasks
  hosts: undercloud-0
  roles:
    - post_install/openstack_tasks
  become: True
  become_method: sudo
  become_user: root


- name: Fluentd tasks
  hosts: opstools-0
  roles:
    - post_install/fluentd_query
  become: True
  become_method: sudo
  become_user: root


- name: Sensu tasks
  hosts: undercloud-0
  roles:
    - post_install/sensu_query
  become: True
  become_method: sudo
  become_user: root
